@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzk0MDQ0NTZ9.CBV78yujGPHqGJj2kLuE43UH6S6Y8AXPt45AaWb2uD4





### Index Exercise
GET http://localhost:3000/exercises.json

### Show Exercise
GET http://localhost:3000/exercises/2.json



### Create Exercise
POST http://localhost:3000/exercises.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Sit ups",
  "description": "test  sit up",
  "image_url": "Situp.com",
  "video_url": "Situpvid.com"
}


### Update Exercise
PATCH http://localhost:3000/exercises/11.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Down ups",
  "description": "test  Down up",
  "image_url": "Situp.com",
  "video_url": "Situpvid.com"
}

### Destroy Exercise
DELETE http://localhost:3000/exercises/10.json


#####-------  LOGIN ------------####

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{

  "name": "Johnny",
  "email": "Johnny@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Session Create (Userlogin)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Johnny@test.com",
  "password": "password"
}
