@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzk0OTQ2ODJ9.1tx-zzoQZ_RzUVYvFsMthqXzIwH8NyswuLytfWinmjg


### Exercise Index
GET http://localhost:3000/exercises.json

### Exercise Show
GET http://localhost:3000/exercises/2.json



### Exercise Create
POST http://localhost:3000/exercises.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Sit ups",
  "description": "test  sit up",
  "image_url": "Situp.com",
  "video_url": "Situpvid.com"
}


### Exercise Update
PATCH http://localhost:3000/exercises/11.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Down ups",
  "description": "test  Down up",
  "image_url": "Situp.com",
  "video_url": "Situpvid.com"
}

### Exercise Destroy
DELETE http://localhost:3000/exercises/10.json




##  LOGIN ------------------------------

### SIGNUP Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{

  "name": "Johnny",
  "email": "Johnny@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### LOGIN Session Create (Userlogin)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Johnny@test.com",
  "password": "password"
}


##  ROUTINE -----------------------------------

### ROUTINE INDEX
GET http://localhost:3000/routines.json

### ROUTINE SHOW
GET http://localhost:3000/routines/2.json

### ROUTINE CREATE
POST http://localhost:3000/routines.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{ 
  "name": "Friday"
}


### ROUTINE UPDATE
PATCH http://localhost:3000/routines/6.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ 
  "name": "SNOW DAY"
}


### ROUTINE DESTROY
DELETE http://localhost:3000/routines/6.json




##  EXERCISE_ROUTINE ----------------------------


### ADD EXERCISE TO ROUTINE

POST http://localhost:3000/exercise_routines.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Sit ups",
  "type": "biceps",
  "muscle": "arms",
  "equipment": "dumbells",
  "difficulty": "beginner",
  "instructions": "Do it like this"
}